### ISSUE TITLE
Show grandchild records?

### ISSUE THREAD

**Issue by solo-1234** [shliachtx/lwc-listview#28]
Is there any chance this could be extended to show grandchild records? In other words, let's say A is a parent of B, B is a parent of C. On an A page I want to show all C records which belong to a B which belong to the A.

I have no idea if this is an easy thing or a big deal, just figured I'd ask :)

Thanks!

**Comment by shliachtx** [comment]
Someone else asked me this same question just now. It is actually relatively trivial. In the example, say you want to see all `Grandchild__c` objects from `Parent__c` the you would use `Parent__c` (from the child) or `Id` (from the parent) as the parent field, and `Child__r.Parent__c` as the child field. The query would end up looking like `SELECT Id... FROM Grandchild__c WHERE Child__r.Parent__c='parentid'`

**Comment by solo-1234** [comment]
That is great - thank you for the update!!
