### ISSUE TITLE
show choices for picklist fields?

### ISSUE THREAD

**Issue by solo-1234** [shliachtx/lwc-listview#3]
Great job on this component! I love how you can do all the config right from within the flexipage editor. 

Is it supposed to support inline editing of picklist fields? When I try to edit a field it lets me type anything (but then it won't save if it's not a valid choice). Is there a way for it to display a dropdown of choices?

**Comment by shliachtx** [comment]
Development has been completed! Will be in the next release

**Comment by solo-1234** [comment]
Awesome! Thank you!!
