### ISSUE TITLE
idea: allow renaming column headers

### ISSUE THREAD

**Issue by solo-1234** [shliachtx/lwc-listview#5]
Here's an idea - allow the user to specify a different column header for a specific field. Sometimes field names are really long and in this context a shorter title would be more user friendly.

**Comment by shliachtx** [comment]
Done. There is now an optional field in the JSON called `label` that will override the default label. This will be available in the next release

**Comment by shliachtx** [comment]
@solo-1234 FYI if you look at the datatable documentation, you can also use a JSON array as input for fields instead of a comma separated list. This gives you more flexibility such as making individual fields editable/sortable

**Comment by solo-1234** [comment]
Awesome! Thanks! Is there a way to be notified when the next version is released?

Thanks for the tip, I will check that out!

**Comment by solo-1234** [comment]
Thanks! I'm not so familiar with json. Are you able to add a simple example with just a couple fields to the readme, so I can copy the format?

If not I will play around and try to figure it out.

Either way - thanks!

**Comment by shliachtx** [comment]
@solo-1234 Done!

**Comment by solo-1234** [comment]
Perfect! Thank you!
